Home/urls.py
from django.urls import path 
from . import views as v

urlpatterns = [
    path('',v.index.as_view()),
    path('403/',v.forbidden.as_view()),
    path('404/',v.not_found.as_view()),


]

Personas/urls.py
from django.urls import path
from .import views as v

app_name="personas"

urlpatterns = [

    #URLS Clientes
    path('clientes/',v.index_personas.as_view(),name="indexCliente"),
    path('clientes/nuevo/',v.ClienteCreateView.as_view(),name="crearCliente"),
    path('clientes/detalles/<pk>/',v.ClienteDetailView.as_view(),name="detalleCliente"),
    path('clientes/actualizar/<pk>/',v.ClienteUpdateView.as_view(),name="actualizarCliente"),
    path('clientes/eliminar/<pk>/',v.ClienteDeleteView.as_view(),name="eliminarCliente"),

    #URLS Proveedores
    path('proveedores/',v.ProveedorListView.as_view(),name="indexProveedor"),
    path('proveedores/nuevo',v.ProveedorCreateView.as_view(),name="crearProveedor"),
    path('proveedores/detalles/<pk>/',v.ProveedorDetailView.as_view(),name="detalleProveedor"),
    path('proveedores/actualizar/<pk>/',v.ProveedorUpdateView.as_view(),name="actualizarProveedor"),
    path('proveedores/eliminar/<pk>/',v.ProveedorDeleteView.as_view(),name="eliminarProveedor"),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from Registration import views as v
from django.conf.urls import handler404, handler500,handler403
urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',v.register,name="register"),
    path('auth/',include("django.contrib.auth.urls")),
    path('',include("Home.urls")),
    path('personas/',include("Personas.urls",namespace="personas")),
    path('gestion/',include("Gestion.urls",namespace="gestion")),
    path('producto/',include("Productos.urls",namespace="producto")),


]
from Home.views import not_found, forbidden

handler404 = not_found.as_view()
handler403 = forbidden.as_view()

templates/Proveedor/create.html
{% extends 'base/body.html' %}


{% block title %}
    Inserción de Proveedores - SIGEVI
{% endblock title %}
    

{%block header%}
    {% if user.is_authenticated %}
    <div class="container-fluid">
        <h1>Formulario de Inserción de Proveedor Nuevo</h1>
    </div>
    {%endif%}
{%endblock header%}

{% block content %}
{% if user.is_authenticated %}
    {%load crispy_forms_tags%}
    <div class="row justify-content-md-center">
        <div class="col col-lg-8">
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-success" type="submit">Guardar</button>
                <a class="btn btn-danger" href="/personas/proveedores/">Cancelar</a>
            </form>
        </div>
    </div>
{% else %}
{% include 'base/login_info.html' %}
{% endif %}
{% endblock content %}


    

templates/Proveedor/delete.html
{% extends 'base/body.html' %}


{% block title %}
    Eliminar de Proveedor - SIGEVI
{% endblock title %}


    

{%block header%}
 
    {% if user.is_authenticated %}
        <div class="container-fluid">
            <h1>Detalles de Cliente {{object.razonSocial}}</h1>
            <hr class="dropdown-divider">
        </div>
        {%else%}


    {%endif%}
{%endblock header%}

{%block content%}

    {% if user.is_authenticated %}
    <form method="POST">
		{%csrf_token%}
		<h3>Se van a eliminar los registros de {{object.razonSocial}} identificado con ID {{object.NIT}}, ¿Continuar?</h3>
        <div class="container-fluid">
            {%if object%}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">NIT</th>
                    <th scope="col">Razón Social</th>
                    <th scope="col">Direccion</th>
                    <th scope="col">Punto de venta</th>
                    <th scope="col">Teléfono</th>     
                    <th scope="col">Correo Electronico</th>      
                </tr>
                </thead>
                <tbody>  
                    <tr>
                        <th scope="row">{{object.NIT}}</th>
                        <td>{{object.razonSocial}}</td>
                        <td>{{object.direccionEmpresa}}</td>
                        <td>{{object.direccionVenta}}</td>
                        <td>{{object.telefono}}</td>
                        <td>{{object.correo}}</td>
                    </tr>
                </tbody>
            </table>
        {%endif%}
    </div>

    {%else%}

    <p>Inicie Sesión para poder ver estos Datos dando clic<strong><a href="/auth/login"> aquí</a></strong></p>

    {%endif%}
		    <td><a class="btn btn-info" href="{% url 'personas:detalleProveedor' object.NIT %}">Regresar a Detalles</a>
            <button class="btn btn-danger" type="submit">Eliminar</button>
            <a class="btn btn-primary" href="/personas/proveedores/">Cancelar y Regresar a Listado General</a>
	</form>

    

        
{%endblock content%}

templates/Proveedor/detail.html
{% extends 'base/body.html' %}


{% block title %}
    Detalle de Proveedor - SIGEVI
{% endblock title %}


    

{%block header%}
 
    {% if user.is_authenticated %}
        <div class="container-fluid">
            <h1>Detalles de Proveedor {{object.razonSocial}}</h1>
            <hr class="dropdown-divider">
        </div>
    {%endif%}
{%endblock header%}

{%block content%}

    {% if user.is_authenticated %}

        <div class="container-fluid">
            {%if object%}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">NIT</th>
                    <th scope="col">Razón Social</th>
                    <th scope="col">Direccion</th>
                    <th scope="col">Punto de venta</th>
                    <th scope="col">Teléfono</th>     
                    <th scope="col">Correo Electronico</th>      
                </tr>
                </thead>
                <tbody>  
                    <tr>
                        <th scope="row">{{object.NIT}}</th>
                        <td>{{object.razonSocial}}</td>
                        <td>{{object.direccionEmpresa}}</td>
                        <td>{{object.direccionVenta}}</td>
                        <td>{{object.telefono}}</td>
                        <td>{{object.correo}}</td>
                    </tr>
                </tbody>
            </table>
               
                <a class="btn btn-primary" href="/personas/proveedores/">Atrás</a>
                <a class="btn btn-warning" href="{% url 'personas:actualizarProveedor' object.NIT %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'personas:eliminarProveedor' object.NIT %}">Borrar</a>
        {%endif%}
    </div>

    

    {%endif%}
    
{%endblock content%}

templates/Proveedor/index.html
{% extends "base/body.html" %}

{% block title %}
Listado General de Proveedores
    
{% endblock title %}


{% block header %}
    {% if user.is_authenticated %}
        <h1>Listado General de Proveedores <a class="btn btn-success" href="{% url 'personas:crearProveedor' %}">Añadir Proveedor nuevo</a>
            </h1>
    
    {% endif %}
{% endblock header %}
    

{% block content %}
    {% if query %}
    <div class="container-fluid">
            <div>
                <form method="get">
                <p>Para Buscar un Proveedor en específico, digite su NIT en la caja de texto y presione el boton buscar <input type="text" name="NIT" > <input type="submit" value="buscar">
                </p>
                </form>
            </div>
        <hr class="dropdown-divider">
    </div>


        <div class="container-fluid">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Identificación</th>
                    <th scope="col">Proveedor</th>
                    <th scope="col">Opciones</th>        
                </tr>
                </thead>
                <tbody>  
                    {% for row in query %}
                    <tr>
                        <th scope="row">{{row.NIT}}</th>
                        <td>{{row.razonSocial}}</td>
                        <td><a class="btn btn-info" href="{% url 'personas:detalleProveedor' row.NIT %}">Info</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
    {% else %}
    <div class="container-fluid">
        <div>
            <form method="get">
            <p>Para Buscar un Proveedor en específico, digite su NIT en la caja de texto y presione el boton buscar <input type="text" name="NIT" > <input type="submit" value="buscar">
            </p>
            </form>
        </div>
    <hr class="dropdown-divider">
</div>   
        <p>No hay registros!, Esto puede pasar por dos razones:</p>
        <p>1. No existen coincidencias con los criterios de búsqueda</p>
        <p>2. No existen Registros o no se puede acceder a ellos</p>
        <p>Si sigue viendo esta pantalla y no ha realizado ninguna consulta, contacte al proveedor del software para mayor información</p>
            
    {% endif %}

    
{% endblock content %}

templates/Proveedor/update.html
{% extends 'base/body.html' %}



{% block title %}
    Actualizar Proveedor - SIGEVI
{% endblock title %}



{%block header%}
    {% if user.is_authenticated %}
    <div class="container-fluid">
        <h1>Formulario de Actualizacion de Proveedor con NIT {{object.NIT}}</h1>
    </div>
    {%else%}
    {%endif%}
{%endblock header%}

{% block content %}
<div class="container">
{% if user.is_authenticated %}
    {%load crispy_forms_tags%}
    <div class="row justify-content-md-center">
        <div class="col col-lg-8">
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <td><a class="btn btn-info" href="{% url 'personas:detalleProveedor' object.NIT %}">Regresar a Detalles</a>
                <button class="btn btn-primary" type="submit">Actualizar</button>
                <a class="btn btn-danger" href="{% url 'personas:indexProveedor' %}">Cancelar y Regresar a Listado General</a>
            </form>
        </div>
    </div>
{% else %}
<h1>inicie sesion para continuar</h1>
{% endif %}
</div>
{% endblock content %}


    