Gestion/urls.py
from django.urls import path
from . import views as v

app_name="gestion"

urlpatterns=[
	#URLS marca
	path('marca/',v.MarcaList.as_view(),name="indexMarca"),
	path('marca/nuevo/',v.MarcaCreate.as_view(),name="crearMarca"),
	path('marca/editar/<pk>/',v.MarcaUpdate.as_view(),name="actualizarMarca"),
	path('marca/eliminar/<pk>/',v.MarcaDelete.as_view(),name="eliminarMarca"),

	#URLS CATEGORIA
	path('categoria/',v.CategoriaList.as_view(),name="indexCategoria"),
	path('categoria/nuevo',v.CategoriaCreate.as_view(),name="crearCategoria"),
	path('categoria/editar/<pk>',v.CategoriaUpdate.as_view(),name="actualizarCategoria"),
	path('categoria/eliminar/<pk>',v.CategoriaDelete.as_view(),name="eliminarCategoria"),

]

Home/urls.py
from django.urls import path 
from . import views as v

urlpatterns = [
    path('',v.index.as_view()),
    path('403/',v.forbidden.as_view()),
    path('404/',v.not_found.as_view()),


]

Personas/urls.py
from django.urls import path
from .import views as v

app_name="personas"

urlpatterns = [

    #URLS Clientes
    path('clientes/',v.index_personas.as_view(),name="indexCliente"),
    path('clientes/nuevo/',v.ClienteCreateView.as_view(),name="crearCliente"),
    path('clientes/detalles/<pk>/',v.ClienteDetailView.as_view(),name="detalleCliente"),
    path('clientes/actualizar/<pk>/',v.ClienteUpdateView.as_view(),name="actualizarCliente"),
    path('clientes/eliminar/<pk>/',v.ClienteDeleteView.as_view(),name="eliminarCliente"),

    #URLS Proveedores
    path('proveedores/',v.ProveedorListView.as_view(),name="indexProveedor"),
    path('proveedores/nuevo',v.ProveedorCreateView.as_view(),name="crearProveedor"),
    path('proveedores/detalles/<pk>/',v.ProveedorDetailView.as_view(),name="detalleProveedor"),
    path('proveedores/actualizar/<pk>/',v.ProveedorUpdateView.as_view(),name="actualizarProveedor"),
    path('proveedores/eliminar/<pk>/',v.ProveedorDeleteView.as_view(),name="eliminarProveedor"),
]

Productos/urls.py
from django.urls import path 
from . import views as v
app_name="producto"
urlpatterns = [
    


    #Gestion de Productos
    path('',v.ProductoList.as_view(),name="productoIndex"),
    path('nuevo/',v.ProductoCreate.as_view(),name="productoCrear"),
    path('detalles/<pk>/',v.ProductoDetail.as_view(),name="productoDetalle"),
    path('actualizar/<pk>/',v.ProductoUpdate.as_view(),name="productoEditar"),
    path('eliminar/<pk>/',v.ProductoDelete.as_view(),name="productoEliminar"),
    path('related/<categoria>/',v.ProductoCategoria,name="productoCategoria"),


    #carrito
    path('agregar/<pk>/',v.agregar_carrito,name="add"),
    path('eliminar/<pk>/',v.eliminar_producto,name="del"),
    path('restar/<pk>/',v.restar_producto,name="remove"),
    path('limpiar/',v.limpiar,name="cls"),
    path('pay/',v.pagar,name="pay"),
    path('PDF/', v.generar_pdf, name="PDF"),

]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from Registration import views as v
from django.conf.urls import handler404, handler500,handler403
urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',v.register,name="register"),
    path('auth/',include("django.contrib.auth.urls")),
    path('',include("Home.urls")),
    path('personas/',include("Personas.urls",namespace="personas")),
    path('gestion/',include("Gestion.urls",namespace="gestion")),
    path('producto/',include("Productos.urls",namespace="producto")),


]
from Home.views import not_found, forbidden

handler404 = not_found.as_view()
handler403 = forbidden.as_view()

templates/base/body.html
{% load static %}
{%load bootstrap5%}
{%bootstrap_css%}
{% load bootstrap_icons %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            
        {% endblock title %}
    </title>
</head>
<body>
    {% include './navbar.html' %}
    {% block header %}
        
    {% endblock header %}
    
    {% block content %}
        
    {% endblock content %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/base/navbar.html
{% load static %}
{%load bootstrap5%}
{%bootstrap_css%}
{% load bootstrap_icons %}

{% if not user.is_anonymous %}
  
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand">SIGEVI</a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">      
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Personas
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'personas:indexCliente' %}">Listado de Clientes</a></li>
            <li><a class="dropdown-item" href="{% url 'personas:crearCliente' %}">Añadir Cliente</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'personas:indexProveedor' %}">Listado de Proveedores</a></li>
            <li><a class="dropdown-item" href="{% url 'personas:crearProveedor' %}">Añadir Proveedores</a></li>

          </ul>
        </li>
        <li class="nav-item">
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Inventario
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'producto:productoIndex' %}">Listado de Productos</a></li>
            <li><a class="dropdown-item" href="{% url 'gestion:crearMarca' %}">Añadir Producto</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'gestion:indexMarca' %}">Listado de Marcas</a></li>
            <li><a class="dropdown-item" href="{% url 'gestion:crearMarca' %}">Añadir Marca</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'gestion:indexCategoria' %}">Listado de Categoría</a></li>
            <li><a class="dropdown-item" href="{% url 'gestion:crearCategoria' %}">Añadir Categoría</a></li>

          </ul>
        </li>
        </li>
      </ul>
    </div>
  </div>
  </div>
    <div class="dropdown">
      
      <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
        Sesión iniciada como {{user.username}}
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
        
        <li><a class="dropdown-item" type="button" href="/auth/logout">Cerrar Sesión{% bs_icon 'power' %}</a></li>
      </ul>
    </div>
</nav>
{% else %}

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand">SIGEVI</a>
    </div>
  </div>
  </div>
</nav>

{% endif %}
  