Gestion/urls.py
from django.urls import path
from . import views as v

app_name="gestion"

urlpatterns=[
	#URLS marca
	path('marca/',v.MarcaList.as_view(),name="indexMarca"),
	path('marca/nuevo/',v.MarcaCreate.as_view(),name="crearMarca"),
	path('marca/editar/<pk>/',v.MarcaUpdate.as_view(),name="actualizarMarca"),
	path('marca/eliminar/<pk>/',v.MarcaDelete.as_view(),name="eliminarMarca"),

	#URLS CATEGORIA
	path('categoria/',v.CategoriaList.as_view(),name="indexCategoria"),
	path('categoria/nuevo',v.CategoriaCreate.as_view(),name="crearCategoria"),
	path('categoria/editar/<pk>',v.CategoriaUpdate.as_view(),name="actualizarCategoria"),
	path('categoria/eliminar/<pk>',v.CategoriaDelete.as_view(),name="eliminarCategoria"),

]

Home/urls.py
from django.urls import path 
from . import views as v

urlpatterns = [
    path('',v.index.as_view()),
    path('403/',v.forbidden.as_view()),
    path('404/',v.not_found.as_view()),


]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from Registration import views as v
from django.conf.urls import handler404, handler500,handler403
urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',v.register,name="register"),
    path('auth/',include("django.contrib.auth.urls")),
    path('',include("Home.urls")),
    path('personas/',include("Personas.urls",namespace="personas")),
    path('gestion/',include("Gestion.urls",namespace="gestion")),
    path('producto/',include("Productos.urls",namespace="producto")),


]
from Home.views import not_found, forbidden

handler404 = not_found.as_view()
handler403 = forbidden.as_view()

templates/Marca/create.html
{% extends 'base/body.html' %}

{% block title %}
    Inserción de Marca - SIGEVI
{% endblock title %}

{%block header%}
    {% if user.is_authenticated %}
    <div class="container-fluid">
        <h1>Formulario de Inserción de Marca Nueva</h1>
    </div>
    {%endif%}
{%endblock header%}

{% block content %}
{% if user.is_authenticated %}
    {%load crispy_forms_tags%}
    <div class="row justify-content-md-center">
        <div class="col col-lg-8">
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-success" type="submit">Guardar</button>
                <a class="btn btn-danger" href="{% url 'gestion:indexMarca' %}">Cancelar</a>
            </form>
        </div>
    </div>
{% else %}
{% include 'base/login_info.html' %}
{% endif %}
{% endblock content %}


    

templates/Marca/delete.html
{% extends 'base/body.html' %}


{% block title %}
    Gestión de Marcas
{% endblock title %}


    

{%block header%}
 
    {% if user.is_authenticated %}
        <div class="container-fluid">
            <h1>Detalles de la Marca {{object.nombre}}</h1>
            <hr class="dropdown-divider">
        </div>
        {%else%}


    {%endif%}
{%endblock header%}

{%block content%}

    {% if user.is_authenticated %}
    <form method="POST">
		{%csrf_token%}
		<h3>Se van a eliminar los registros de {{object.nombre}} y sus registros conexos, ¿Continuar?</h3>
        <div class="container-fluid">
    </form>

    {%else%}

    <p>Inicie Sesión para poder ver estos Datos dando clic<strong><a href="/auth/login"> aquí</a></strong></p>

    {%endif%}
		    <td>
            <button class="btn btn-danger" type="submit">Eliminar</button>
            <a class="btn btn-primary" href="{% url 'gestion:indexMarca' %}">Cancelar y Regresar a Listado General</a>
	</form>

    

        
{%endblock content%}

templates/Marca/index.html
{% extends "base/body.html" %}

{% block title %}
Listado de Marcas - SIGEVI
    
{% endblock title %}


{% block header %}
    <h1>Listado General de Marcas <a class="btn btn-success" href="{% url 'gestion:crearMarca' %}">Agregar Marca</a></h1>
{% endblock header %}
    

{% block content %}
    {% if query %}
    <div class="container-fluid">
            <div>
                <form method="get">
                <p>Para Buscar una marca en específico, digite su nombre en la caja de texto y presione el boton buscar <input type="text" name="marca" > <input type="submit" value="buscar">
                </p>
                </form>
            </div>
        <hr class="dropdown-divider">
    </div>


        <div class="container-fluid">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Marca</th>
                    
                    <th scope="col">Opciones</th>        
                </tr>
                </thead>
                <tbody>  
                    {% for row in query %}
                    <tr>
                        <th scope="row">{{row.id}}</th>
                        <td>{{row.nombre}}</td>
                        
                        <td>
                        <a class="btn btn-warning" href="{% url 'gestion:actualizarMarca' row.id %}">Editar</a>
                        <a class="btn btn-danger" href="{% url 'gestion:eliminarMarca' row.id %}">Eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
    {% else %}
    <div class="container-fluid">
        <div>
            <form method="get">
            <p>Para Buscar una marca en específico, digite su identificacion en la caja de texto y presione el boton buscar <input type="text" name="marca" > <input type="submit" value="buscar">
            </p>
            </form>
        </div>
    <hr class="dropdown-divider">
</div>   
        <p>No hay registros!, Esto puede pasar por dos razones:</p>
        <p>1. No existen coincidencias con los criterios de búsqueda</p>
        <p>2. No existen Registros o no se ṕuede acceder a ellos</p>
        <p>Si sigue viendo esta pantalla y no ha realizado ninguna consulta, contacte al proveedor del software para mayor información</p>
           
    {% endif %}
            

    
{% endblock content %}

templates/Marca/update.html
{% extends 'base/body.html' %}



{% block title %}
    Gestión de Marcas
{% endblock title %}



{%block header%}
    {% if user.is_authenticated %}
    <div class="container-fluid">
        <h1>Formulario de Actualizacion de Marca</h1>
    </div>
    {%endif%}
{%endblock header%}

{% block content %}
<div class="container">
{% if user.is_authenticated %}
    {%load crispy_forms_tags%}
    <div class="row justify-content-md-center">
        <div class="col col-lg-8">
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-primary" type="submit">Actualizar</button>
                <a class="btn btn-danger" href="{% url 'gestion:indexMarca' %}">Cancelar y Regresar a Listado General</a>
            </form>
        </div>
    </div>
{% else %}
<h1>inicie sesion para continuar</h1>
{% endif %}
</div>
{% endblock content %}


    